# Generated by Django 4.0.6 on 2022-07-07 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('city', models.CharField(max_length=50)),
                ('text', models.TextField()),
                ('tajrobeh', models.CharField(max_length=20)),
                ('count_project', models.CharField(max_length=20)),
            ],
        ),
    ]
