# Generated by Django 4.0.6 on 2022-08-01 13:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contact_by_me', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact_by_me',
            name='addres',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_by_me',
            name='email',
            field=models.EmailField(default=1, max_length=254),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_by_me',
            name='phone',
            field=models.CharField(default=1, max_length=20),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact_by_me',
            name='telegram',
            field=models.CharField(default='https://tlgrm.me/', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_by_me',
            name='whatsapp',
            field=models.CharField(default='https://wa/me/', max_length=100),
        ),
        migrations.AddField(
            model_name='contact_by_me',
            name='yotube',
            field=models.CharField(default='https://www.youtube.com/', max_length=100),
        ),
    ]
