# Generated by Django 4.0.6 on 2022-07-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Working',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('titel', models.CharField(max_length=50)),
                ('image', models.ImageField(upload_to='Myworking/img')),
            ],
        ),
    ]
