# Generated by Django 4.0.6 on 2022-07-07 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='maharat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('langoag', models.CharField(max_length=50)),
                ('count_langoag', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='resume',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
