# Generated by Django 4.0.6 on 2022-07-07 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('My_resume', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='eduction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titel', models.CharField(max_length=50)),
                ('data', models.CharField(max_length=100)),
                ('text', models.TextField()),
            ],
        ),
    ]
