# Generated by Django 4.0.6 on 2022-07-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Blog_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='wrter',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
